# Importing Libraries

In [41]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

# Closed Form Solution
## Simple Linear Regression using (OLS) Ordinary Least Square

In [55]:
df = pd.read_csv('/content/cgpa_lpa_dataset.csv')
df.head()

cgpa    lpa
0  8.48  26.53
1  6.43  19.43
2  6.13  20.30
3  7.76  19.85
4  8.60  23.44

In [60]:
X = df.drop('lpa',axis=1)
Y = df['lpa']

X_train , X_test , y_train , y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

In [61]:
lr = LinearRegression()
lr.fit(X_train,y_train)
lr.predict(X_test)

array([19.37530719, 19.73490227, 22.52867946, 25.04584505, 24.76923344,
       18.71143934, 25.51608477, 16.88580277, 19.40296835, 29.83122577,
       16.69217464, 23.85641515, 17.32838133, 22.74996874, 27.53534947,
       28.86308516, 20.81368752, 17.35604249, 22.39037366, 24.27133256,
       20.37110896, 23.69044819, 27.42470483, 17.82628222, 22.72230758,
       21.56053885, 29.83122577, 25.29479549, 17.52200945, 16.27725724,
       18.29652194, 16.74749696, 21.06263797, 26.65019234, 17.19007553,
       28.64179588, 22.44569598, 29.30566373, 16.27725724, 21.36691073,
       17.60499293, 17.21773669, 17.66031525, 26.15229146, 28.91840748,
       16.13895144, 26.17995262, 20.73070404, 18.24119962, 17.16241437,
       16.66451348, 16.13895144, 29.66525881, 21.75416697, 26.84382046,
       20.81368752, 22.14142322, 17.74329873, 19.34764603, 23.82875399])

In [78]:
lr.coef_

array([2.76611603])

In [79]:
lr.intercept_

np.float64(2.225387822572138)

# Non Closed Form Solution
## Simple Linear Regression using Gradient Descent

In [189]:
class GDRegressor:
  def __init__(self , learning_rate , epochs):
    self.m = 0.0
    self.b = 0.0
    self.learning_rate = learning_rate
    self.epochs = epochs

  def fit(self, X_train , y_train):
    X_train = np.array(X_train)
    y_train = np.array(y_train)
    n = X_train.shape[0]

    for i in range(self.epochs):
      val1 = 0
      val2 = 0

      for j in range(X_train.shape[0]):
        val1 += (y_train[j] - (self.m * X_train[j]) - self.b)

      slope_b = -(2.0 / n) * val1;

      for j in range(X_train.shape[0]):
        val2 += (X_train[j] * ((y_train[j] - (self.m * X_train[j])) - self.b))

      slope_m = -(2.0 / n) * val2;

      self.m = self.m - self.learning_rate * slope_m
      self.b = self.b - self.learning_rate * slope_b

  def predict(self, X_test):
    return ((self.m * X_test) + self.b)

In [190]:
gdr = GDRegressor(0.01 , 9000)
gdr.fit(X_train,y_train)
gdr.predict(X_test)

cgpa
98   19.373645
259  19.733372
184  22.528175
256  25.046264
29   24.769551
254  18.709533
7    25.516676
13   16.883227
230  19.401316
91   29.833401
284  16.689528
127  23.856398
30   17.325968
241  22.749545
113  27.536682
84   28.864905
99   20.812553
140  17.353639
144  22.389818
94   24.271467
35   20.369812
3    23.690370
173  27.425997
175  17.824051
215  22.721874
89   21.559679
203  29.833401
193  25.295306
266  17.519667
281  16.274458
131  18.294464
209  16.744870
271  21.061595
161  26.651200
176  17.187611
174  28.643535
245  22.445161
289  29.307646
74   16.274458
109  21.365979
155  17.602681
65   17.215283
41   17.658024
11   26.153116
293  28.920248
240  16.136101
130  26.180788
114  20.729539
77   18.239121
171  17.159940
235  16.661856
272  16.136101
134  29.667373
214  21.753378
151  26.844899
10   20.812553
159  22.140776
199  17.741038
232  19.345974
180  23.828726

In [191]:
gdr.b

array([2.21743123])

In [192]:
gdr.m

array([2.76713124])